package com.example.demo002.service;

import com.alibaba.fastjson2.JSON;
import com.alibaba.fastjson2.JSONArray;
import lombok.extern.slf4j.Slf4j;
import org.apache.commons.lang3.StringUtils;
import org.dom4j.*;
import java.util.*;
import java.util.regex.Pattern;
import com.alibaba.fastjson2.JSONObject;
@Slf4j
public class Xml2Json {


        // 解决 CDATA 问题
        private static Pattern pattern = Pattern.compile("[<>&\"',]");

        public static String toXml(Object obj) {
            return jsonStr2Xml(JSON.toJSONString(obj));
        }

        private static String escape(String string) {
            return pattern.matcher(string).find() ? "<![CDATA[" + string + "]]>" : string;
        }

        /**
         * updateXml
         * @param xmlStr
         */
        private static String updateXml(String xmlStr) {
            xmlStr = xmlStr.trim();
            if (StringUtils.isBlank(xmlStr)) {
                return xmlStr;
            }

            // 过滤非法字符
            xmlStr = xmlStr.replaceAll("[\\x00-\\x08\\x0b-\\x0c\\x0e-\\x1f]", "");

            StringBuilder xmlSb = new StringBuilder(xmlStr);
            if (!xmlStr.startsWith("<?")) {
                xmlSb.insert(0, "<?xml version=\"1.0\" encoding=\"utf-8\"?>");
            }

            int idx = xmlSb.indexOf("?>") + 2;
            xmlSb.insert(idx, "<root_luxsun>").append("</root_luxsun>");

            return xmlSb.toString();
        }

        /**
         * xml2Json
         * @param xmlStr
         * @return
         * @throws DocumentException
         */
        public static JSONObject toJson(String xmlStr) throws DocumentException {
            xmlStr = updateXml(xmlStr);
            Document doc = DocumentHelper.parseText(xmlStr);
            JSONObject json = new JSONObject();
            dom4j2Json(doc.getRootElement(), json);
            return json;
        }

        /**
         * toJsonString
         * @param xmlStr
         */
        public static String toJsonString(String xmlStr) throws DocumentException {
            JSONObject jsonObject = toJson(xmlStr);
            String json = JSON.toJSONString(jsonObject);
            return json;
        }

        /**
         * toMap
         * @param xmlStr
         */
        public static Map<String, Object> toMap(String xmlStr) throws DocumentException {
            String jsonStr = toJsonString(xmlStr);
            Map<String, Object> xmlMap = JSON.parseObject(jsonStr, LinkedHashMap.class);
            return xmlMap;
        }

        /**
         * xml转json
         * @param element
         * @param json
         */
        private static void dom4j2Json(Element element, JSONObject json){
            // 如果是属性
            for(Object o:element.attributes()){
                Attribute attr=(Attribute)o;
                if(!isEmpty(attr.getValue())){
                    json.put("@"+attr.getName(), attr.getValue());
                }
            }
            List<Element> chdEl=element.elements();
            if(chdEl.isEmpty()&&!isEmpty(element.getText())){ // 如果没有子元素,只有一个值
                json.put(element.getName(), element.getText());
            }

            for(Element e:chdEl){ // 有子元素
                if(!e.elements().isEmpty()){ // 子元素也有子元素
                    JSONObject chdjson=new JSONObject();
                    dom4j2Json(e,chdjson);
                    Object o=json.get(e.getName());
                    if(o!=null){
                        JSONArray jsona=null;
                        if(o instanceof JSONObject){ // 如果此元素已存在,则转为jsonArray
                            JSONObject jsono=(JSONObject)o;
                            json.remove(e.getName());
                            jsona=new JSONArray();
                            jsona.add(jsono);
                            jsona.add(chdjson);
                        }
                        if(o instanceof JSONArray){
                            jsona=(JSONArray)o;
                            jsona.add(chdjson);
                        }
                        json.put(e.getName(), jsona);
                    }else{
                        if(!chdjson.isEmpty()){
                            json.put(e.getName(), chdjson);
                        }
                    }
                }else{ // 子元素没有子元素
                    for(Object o:element.attributes()){
                        Attribute attr=(Attribute)o;
                        if(!isEmpty(attr.getValue())){
                            json.put("@"+attr.getName(), attr.getValue());
                        }
                    }
                    if(!e.getText().isEmpty()){
                        json.put(e.getName(), e.getText());
                    }
                }
            }
        }

        public static boolean isEmpty(String str) {

            if (str == null || str.trim().isEmpty() || "null".equals(str)) {
                return true;
            }
            return false;
        }

        /**
         * jsonStr2Xml
         * @param json
         * @return java.lang.String
         */
        public static String jsonStr2Xml(String json){
            try {
                StringBuffer buffer = new StringBuffer();
                buffer.append("<?xml version=\"1.0\" encoding=\"utf-8\"?>");
                JSONObject jObj = JSON.parseObject(json);
                json2Xmlstr(jObj,buffer);
                return buffer.toString();
            }
            catch (Exception e) {
                e.printStackTrace();
                return "";
            }
        }

        /**
         * Json to xmlstr string
         *
         * @param jObj   the j obj
         * @param buffer the buffer
         * @return the string
         */
        public static String json2Xmlstr(JSONObject jObj,StringBuffer buffer){
            Set<Map.Entry<String, Object>> se = jObj.entrySet();
            for(Iterator<Map.Entry<String, Object>> it = se.iterator(); it.hasNext(); )
            {
                Map.Entry<String, Object> en = it.next();
                if(en.getValue().getClass().getName().equals("com.alibaba.fastjson.JSONObject")){
                    buffer.append("<"+en.getKey()+">");
                    JSONObject jo = jObj.getJSONObject(en.getKey());
                    json2Xmlstr(jo,buffer);
                    buffer.append("</"+en.getKey()+">");
                }else if(en.getValue().getClass().getName().equals("com.alibaba.fastjson.JSONArray")){
                    JSONArray jarray = jObj.getJSONArray(en.getKey());
                    for (int i = 0; i < jarray.size(); i++) {
                        buffer.append("<"+en.getKey()+">");
                        JSONObject jsonobject =  jarray.getJSONObject(i);
                        json2Xmlstr(jsonobject,buffer);
                        buffer.append("</"+en.getKey()+">");
                    }
                }else if(en.getValue().getClass().getName().equals("java.lang.String")){
                    buffer.append("<"+en.getKey()+">" + escape((String) en.getValue()));
                    buffer.append("</"+en.getKey()+">");
                }
            }
            return buffer.toString();
        }

        public static void main(String[] args) throws DocumentException {
            String xmlStr = "<?xml version=\"1.0\" encoding=\"UTF-8\"?><DATA><BILLID>8fa07a747a1ada135fd0b57e5dc1cb21</BILLID><ORDERLIST><ITEM><UID>ZI4MF5JO</UID><ORDERNO>nm48V9qfhSe7b5dO9Ov</ORDERNO><KEY>天津乖乖投资控股集团有限公司</KEY><KEYTYPE>2</KEYTYPE><STATUS>1</STATUS><FINISHTIME>2020-12-03 11:19:25</FINISHTIME></ITEM></ORDERLIST><ALTER><ITEM><ALTDATE>2011-03-14</ALTDATE><ALTITEMCODE>69</ALTITEMCODE><ALTITEM>名称变更(字号名称、集团名称等)</ALTITEM><ALTBE><![CDATA[<font color=\"red\">嘉年华</font>]]></ALTBE><ALTAF><![CDATA[<font color=\"red\">乖乖</font>]]></ALTAF><RECORD_ID>df9fe8e159e8d96c9d3b021cfe555228</RECORD_ID></ITEM><ITEM><ALTDATE>2011-03-14</ALTDATE><ALTITEMCODE>69</ALTITEMCODE><ALTITEM>名称变更(字号名称、集团名称等)</ALTITEM><ALTBE><![CDATA[天津<font color=\"red\">嘉年华</font>投资有限公司]]></ALTBE><ALTAF><![CDATA[天津<font color=\"red\">乖乖</font>投资<font color=\"red\">控股集团</font>有限公司]]></ALTAF><RECORD_ID>0b2df2540ebd1704928de651bd9010d8</RECORD_ID></ITEM></ALTER><BREAKLAW></BREAKLAW><CASEINFO></CASEINFO><ENTCASEBASEINFO></ENTCASEBASEINFO><DEALIN><ITEM><ANCHEYEAR>2012</ANCHEYEAR><BUSST>开业</BUSST><VENDINC>0</VENDINC><SERVINC>4.55</SERVINC><PROGRO>0.77</PROGRO><RATGRO>0</RATGRO><NETINC>0.77</NETINC><DEFICIT>0</DEFICIT><ASSGRO>39242.88</ASSGRO><LTERMINV>32107.89</LTERMINV><LIAGRO>36686.59</LIAGRO><LTERMLIAAM>0</LTERMLIAAM><CURRENCY>人民币元</CURRENCY></ITEM><ITEM><ANCHEYEAR>2009</ANCHEYEAR><BUSST>开业</BUSST><VENDINC>0</VENDINC><SERVINC>0</SERVINC><PROGRO>0.2</PROGRO><RATGRO>0</RATGRO><NETINC>0</NETINC><DEFICIT>0.14</DEFICIT><ASSGRO>20378.87</ASSGRO><LTERMINV>18254.09</LTERMINV><LIAGRO>17814.67</LIAGRO><LTERMLIAAM>0</LTERMLIAAM><CURRENCY>人民币元</CURRENCY></ITEM></DEALIN><BASIC><ITEM><ENTNAME>天津乖乖投资控股集团有限公司</ENTNAME><ID>120000120191004120070717000121949100100000015399817</ID><ENTNAMEENG>天津乖乖投资控股集团有限公司</ENTNAMEENG><ENTNAME_OLD>天津嘉年华投资有限公司</ENTNAME_OLD><ORGCODES>663083409</ORGCODES><CREDITCODE>911201166630834097</CREDITCODE><REGNO>120191000002366</REGNO><ORIREGNO></ORIREGNO><FRNAME>张贵富</FRNAME><REGCAP>2800.000000</REGCAP><REGCAPCURCODE>156</REGCAPCURCODE><REGCAPCUR>人民币元</REGCAPCUR><ESDATE>2007-07-17</ESDATE><OPFROM>2007-07-17</OPFROM><OPTO>2037-07-16</OPTO><ENTITYTYPE>1</ENTITYTYPE><ENTTYPE>有限责任公司</ENTTYPE><ENTSTATUS>在营（开业）</ENTSTATUS><ENTSTATUSCODE>1</ENTSTATUSCODE><ABUITEM>以自有资金对工业、商业、能源建设、交通运输、房地产、装修装饰、证券行业、仓储服务、高新技术产业的投资。（依法须经批准的项目，经相关部门批准后方可开展经营活动）</ABUITEM><ZSOPSCOPE>以自有资金对工业、商业、能源建设、交通运输、房地产、装修装饰、证券行业、仓储服务、高新技术产业的投资。（依法须经批准的项目，经相关部门批准后方可开展经营活动）</ZSOPSCOPE><REGORG>天津市滨海新区市场监督管理局</REGORG><ANCHEYEAR>2018</ANCHEYEAR><PALGORITHMID><![CDATA[V1!Tw6F42WN+ZJTys2CCSBBMxafaWhfIxn/onWVvymTaTOMKqlRjLV8nrCMcfEDoapU6QCylhEvhedl<n>IugYRVDaUw==]]></PALGORITHMID><EMID>292dad4f1b2cf81ffd40fe86e6d93ab9</EMID><CANDATE></CANDATE><REVDATE></REVDATE><RECCAP>2800.000000</RECCAP><EMPNUM>0</EMPNUM><ChangeDate>2011-03-14</ChangeDate><APPRDATE>2011-03-14</APPRDATE><ENTTYPECODE>1100</ENTTYPECODE><INDUSTRYCOCODE>676</INDUSTRYCOCODE><INDUSTRYCONAME>资本投资服务</INDUSTRYCONAME><INDUSTRYCO>676</INDUSTRYCO><INDUSTRYCOALL>676资本投资服务</INDUSTRYCOALL><INDUSTRYPHY>金融业</INDUSTRYPHY><INDUSTRYPHYALL>J金融业</INDUSTRYPHYALL><INDUSTRYPHYCODE>J</INDUSTRYPHYCODE><INDUSTRYPHYNAME>金融业</INDUSTRYPHYNAME><TEL>022-66253373</TEL><DOM>天津开发区黄海路19号0130</DOM><REGORGCODE>120116</REGORGCODE><ANCHEDATE></ANCHEDATE><DOMDISTRICT>120116</DOMDISTRICT><OPSCOPE>以自有资金对工业、商业、能源建设、交通运输、房地产、装修装饰、证券行业、仓储服务、高新技术产业的投资。（依法须经批准的项目，经相关部门批准后方可开展经营活动）</OPSCOPE><PERSON_ID_BOCOM></PERSON_ID_BOCOM><REGORGPROVINCE>天津市</REGORGPROVINCE><REGORGCITY>天津市</REGORGCITY><REGCITY>120000</REGCITY><REGORGDISTRICT>天津市滨海新区</REGORGDISTRICT><EMAIL></EMAIL><POSTALCODE>300457</POSTALCODE><CBUITEM>以自有资金对工业、商业、能源建设、交通运输、房地产、装修装饰、证券行业、仓储服务、高新技术产业的投资。（依法须经批准的项目，经相关部门批准后方可开展经营活动）</CBUITEM><CERTYPECODE></CERTYPECODE><CERTYPE></CERTYPE><OPLOC>天津开发区黄海路19号0130</OPLOC><OPSCOANDFORM></OPSCOANDFORM><S_EXT_NODENUM>120000</S_EXT_NODENUM><TAX_CODE>911201166630834097</TAX_CODE><COUNTRYCODE>156</COUNTRYCODE><COUNTRY>中国</COUNTRY><QRCODE_IMAGE_BASE64>iVBORw0KGgoAAAANSUhEUgAAASwAAAEsAQAAAABRBrPYAAADZ0lEQVR42u2aQYrjQAxFFbLw0keom8QXM9jQF0tuUkfw0gsTzf9fNuN0z2KYVYlxoBsSvywKSV9fqpj/zWuxC7uwC/sPsWpmd19vixUbfCt2W6bqb5vqiieWAsPfV7WH3Wv37L9qp7eDz7YO8bR9bLX+y/3lc8EnOOTL8fZto638ahqsdq/l7t2LwRqWyc36reTCkG8g1mFBhj362Zh0ngdTvoF11g2Lh8F6sox+pmWjGKu+rg9E7Pu/H+LQKBYvo3B1rpMuY9GZ/yDRbWI4KRLsSDqkmgR4QMRQRmPJgDlkdzRqFmtkombhkFBhPOg3y4EhTubvXvU/F0pYVZD0NgXGhq1+QdkdrVP7cN9QL/05LVvGnjiQsgzayw7I9sHMg3qNlgLDiSLfVDyle7OCBkQM+fZbe1vG4J2i721hPNQ+QgmUiAkw5Zt8CN3gzI8gXLu92koKjNEpqHpo73BEjM9YPCfhahlbb1Eo6nvIvBdZ1j++mgOrOpXvwYL7IKFObjQjKTCdjzaWIULXhvZWaRZek2fA9kbH1k3jATseVc8espy0t2XMOFFoKGKcQnujA8KW1AwYPbkhwaJ4jEPR3S1eOm4CbGWj655GT444aUYiUSVmKTB9JAHmMMF5aHL17/VsaFvGdDRi6HuPmEo3zkjU3m9V3yyGh8Z5yGMg5VDEdZMM7VxSYNxx0EXJk9+5McNDtcF9SG0eU2VEsGKzcXjyMCMpMGmWLCFDVbRuCk9+848m3ix27DgiYqgRrv/oziXAJQOGOCHVuKahlZIJn2P99+kGG8Zca5rYtTI6HfcFNILOvuI5MIaIJnwvmTdD9JYFWU52pWUs1sWmawgQrCBdQxS+tRSYThqKy6OtIvYLiXP7aBer2tV0T3lyveUlCnc1h7VtH+ND7SjLsaGR9lrxff3XPObc1ZTjGkIhohLIEp7zrWWMkxGnoNjhs4lHG4yvZsCiwpllJSajIeRKI9OUAtOLhWLKN8bpXpV5n568YSzus8KT046rf3MLjsno7ENaxnir6AqW6aS8B/LX7nQ9Bbbu4/Rxt7svy2ZNRpYHk2bJT3WcMnRm+9iTN49pIF11OafWzVV46FgGLH5tIi8b10LU3lssL7+VTKuY7Uo18rcZipjHhYT6Sgbs+o3ZhV3Yhf0r9gtcs9N0f09VEgAAAABJRU5ErkJggg==</QRCODE_IMAGE_BASE64><UPDATEDATE>20200219</UPDATEDATE><IDENTITYCARDNT></IDENTITYCARDNT><IDENTITY></IDENTITY><LOGOIMGNAME>CKiAubNCQfhnWCwDRBTrHsN6VT9y4bHrZMfCXAM3S7B29emdDzqrKxc</LOGOIMGNAME><ENTID>8fa07a747a1ada135fd0b57e5dc1cb21</ENTID><OTHERTEL></OTHERTEL><COORDINATE><![CDATA[117.687365,39.03323]]></COORDINATE><BAIDU_COORDINATE><![CDATA[117.694181,39.03903]]></BAIDU_COORDINATE></ITEM></BASIC><ENT_HANGYEINFO><ITEM><INDUSTRYPHYNAME>金融业</INDUSTRYPHYNAME><INDUSTRYCOCODE>676</INDUSTRYCOCODE><INDUSTRYCONAME>资本投资服务</INDUSTRYCONAME><INDUSTRYPHY>金融业</INDUSTRYPHY><ENTNAME>天津乖乖投资控股集团有限公司</ENTNAME></ITEM></ENT_HANGYEINFO><ENT_BIAOSHIINFO><ITEM><ORGCODES>663083409</ORGCODES><ENTNAME>天津乖乖投资控股集团有限公司</ENTNAME></ITEM></ENT_BIAOSHIINFO><ENT_ZONGHEINFO><ITEM><ENTNAME>天津乖乖投资控股集团有限公司</ENTNAME><INDUSTRYPHYCODE>J</INDUSTRYPHYCODE><INDUSTRYPHYNAME>金融业</INDUSTRYPHYNAME><INDUSTRYPHYALL>J金融业</INDUSTRYPHYALL><INDUSTRYCOALL>676资本投资服务</INDUSTRYCOALL><EMPNUM>0</EMPNUM><ENTNAMEENG>天津乖乖投资控股集团有限公司</ENTNAMEENG><REGORGPROVINCE>天津市</REGORGPROVINCE><REGORGCODE>120116</REGORGCODE><INDUSTRYPHY>金融业</INDUSTRYPHY><OPLOC>天津开发区黄海路19号0130</OPLOC><S_EXT_NODENUM>120000</S_EXT_NODENUM><DOMDISTRICT>120116</DOMDISTRICT><ANCHEDATE></ANCHEDATE><RECCAP>2800.000000</RECCAP><ABUITEM>以自有资金对工业、商业、能源建设、交通运输、房地产、装修装饰、证券行业、仓储服务、高新技术产业的投资。（依法须经批准的项目，经相关部门批准后方可开展经营活动）</ABUITEM><CBUITEM>以自有资金对工业、商业、能源建设、交通运输、房地产、装修装饰、证券行业、仓储服务、高新技术产业的投资。（依法须经批准的项目，经相关部门批准后方可开展经营活动）</CBUITEM><OPSCOANDFORM></OPSCOANDFORM><ANCHEYEAR>2018</ANCHEYEAR></ITEM></ENT_ZONGHEINFO><ENTINV><ITEM><ENTID>edf44df928988a7049f5ebca8c777bb2</ENTID><REGNO>120118000032322</REGNO><ENTTYPE>有限责任公司(自然人投资或控股的法人独资)</ENTTYPE><REGCAP>1000.000000</REGCAP><REGCAPCUR>人民币元</REGCAPCUR><ENTSTATUS>在营（开业）</ENTSTATUS><REGORG>市自贸区市场监管局</REGORG><SUBCONAM>1000.000000</SUBCONAM><CONGROCUR>人民币元</CONGROCUR><FUNDEDRATIO>100.00%</FUNDEDRATIO><ESDATE>2015-07-01</ESDATE><NAME>张贵富</NAME><BINVVAMOUNT>7</BINVVAMOUNT><CANDATE></CANDATE><REVDATE></REVDATE><CONFORM>货币</CONFORM><REGORGCODE>120118</REGORGCODE><CREDITCODE>91120118341040772F</CREDITCODE><INDUSTRYCOCODE>5292</INDUSTRYCOCODE><INDUSTRYCONAME>互联网零售</INDUSTRYCONAME><ENTNAME>天津乖乖数位电子商务有限公司</ENTNAME></ITEM><ITEM><ENTID>067b404a6876bd072b03fe32ee17450a</ENTID><REGNO>120000400073350</REGNO><ENTTYPE>有限责任公司(中外合资)</ENTTYPE><REGCAP>3895.885400</REGCAP><REGCAPCUR>美元</REGCAPCUR><ENTSTATUS>在营（开业）</ENTSTATUS><REGORG>天津市滨海新区市场监督管理局</REGORG><SUBCONAM>2898.538700</SUBCONAM><CONGROCUR>美元</CONGROCUR><FUNDEDRATIO>74.40%</FUNDEDRATIO><ESDATE>1993-04-26</ESDATE><NAME>萧淑蕊</NAME><BINVVAMOUNT>7</BINVVAMOUNT><CANDATE></CANDATE><REVDATE></REVDATE><CONFORM>货币</CONFORM><REGORGCODE>120116</REGORGCODE><CREDITCODE>91120116600515788K</CREDITCODE><INDUSTRYCOCODE>1499</INDUSTRYCOCODE><INDUSTRYCONAME>其他未列明食品制造</INDUSTRYCONAME><ENTNAME>嘉年华(天津)国际有限公司</ENTNAME></ITEM><ITEM><ENTID>bac5c81cfbbb156cc6c1d6908a6d4318</ENTID><REGNO>120224000036617</REGNO><ENTTYPE>有限责任公司(外商投资企业投资)</ENTTYPE><REGCAP>550.000000</REGCAP><REGCAPCUR>人民币元</REGCAPCUR><ENTSTATUS>在营（开业）</ENTSTATUS><REGORG>天津市宝坻区市场监督管理局</REGORG><SUBCONAM>525.000000</SUBCONAM><CONGROCUR>人民币元</CONGROCUR><FUNDEDRATIO>95.45%</FUNDEDRATIO><ESDATE>2008-11-20</ESDATE><NAME>萧淑蕊</NAME><BINVVAMOUNT>7</BINVVAMOUNT><CANDATE></CANDATE><REVDATE></REVDATE><CONFORM>货币</CONFORM><REGORGCODE>120224</REGORGCODE><CREDITCODE>91120224681868322N</CREDITCODE><INDUSTRYCOCODE>5121</INDUSTRYCOCODE><INDUSTRYCONAME>米、面制品及食用油批发</INDUSTRYCONAME><ENTNAME>天津乖乖粮油有限公司</ENTNAME></ITEM><ITEM><ENTID>8e3378efb8de4965208b37146fe12989</ENTID><REGNO>120118000032339</REGNO><ENTTYPE>有限责任公司(自然人投资或控股的法人独资)</ENTTYPE><REGCAP>1000.000000</REGCAP><REGCAPCUR>人民币元</REGCAPCUR><ENTSTATUS>在营（开业）</ENTSTATUS><REGORG>市自贸区市场监管局</REGORG><SUBCONAM>1000.000000</SUBCONAM><CONGROCUR>人民币元</CONGROCUR><FUNDEDRATIO>100.00%</FUNDEDRATIO><ESDATE>2015-07-01</ESDATE><NAME>张贵富</NAME><BINVVAMOUNT>7</BINVVAMOUNT><CANDATE></CANDATE><REVDATE></REVDATE><CONFORM>货币</CONFORM><REGORGCODE>120118</REGORGCODE><CREDITCODE>91120118341040756R</CREDITCODE><INDUSTRYCOCODE>7259</INDUSTRYCOCODE><INDUSTRYCONAME>其他广告服务</INDUSTRYCONAME><ENTNAME>天津嘉年华数位广告传媒有限公司</ENTNAME></ITEM><ITEM><ENTID>b54d48b43acc3b203b847cc381a11a0f</ENTID><REGNO>120224000035358</REGNO><ENTTYPE>有限责任公司</ENTTYPE><REGCAP>50.000000</REGCAP><REGCAPCUR>人民币元</REGCAPCUR><ENTSTATUS>注销</ENTSTATUS><REGORG>天津市宝坻区市场监督管理局</REGORG><SUBCONAM>25.000000</SUBCONAM><CONGROCUR>人民币元</CONGROCUR><FUNDEDRATIO>50.00%</FUNDEDRATIO><ESDATE>2008-10-15</ESDATE><NAME>张贵富</NAME><BINVVAMOUNT>7</BINVVAMOUNT><CANDATE>2011-08-22</CANDATE><REVDATE></REVDATE><CONFORM></CONFORM><REGORGCODE>120224</REGORGCODE><CREDITCODE></CREDITCODE><INDUSTRYCOCODE>3531</INDUSTRYCOCODE><INDUSTRYCONAME>食品、酒、饮料及茶生产专用设备制造</INDUSTRYCONAME><ENTNAME>天津嘉年华水处理设施制造有限公司</ENTNAME></ITEM><ITEM><ENTID>a4355de9e42273b8fca16a314b6a70e9</ENTID><REGNO>120000400038277</REGNO><ENTTYPE>有限责任公司(台港澳与境内合资)</ENTTYPE><REGCAP>2017.647000</REGCAP><REGCAPCUR>美元</REGCAPCUR><ENTSTATUS>在营（开业）</ENTSTATUS><REGORG>天津市宝坻区市场监督管理局</REGORG><SUBCONAM>1008.823500</SUBCONAM><CONGROCUR>美元</CONGROCUR><FUNDEDRATIO>50.00%</FUNDEDRATIO><ESDATE>2007-12-17</ESDATE><NAME>萧淑蕊</NAME><BINVVAMOUNT>7</BINVVAMOUNT><CANDATE></CANDATE><REVDATE></REVDATE><CONFORM>货币</CONFORM><REGORGCODE>120224</REGORGCODE><CREDITCODE>911202246688230745</CREDITCODE><INDUSTRYCOCODE>1441</INDUSTRYCOCODE><INDUSTRYCONAME>液体乳制造</INDUSTRYCONAME><ENTNAME>乖乖嘉年华(天津)食品有限公司</ENTNAME></ITEM><ITEM><ENTID>3d6c6f58e45b81874095984b69d761c3</ENTID><REGNO>120107000052199</REGNO><ENTTYPE>有限责任公司(自然人投资或控股的法人独资)</ENTTYPE><REGCAP>12000.000000</REGCAP><REGCAPCUR>人民币元</REGCAPCUR><ENTSTATUS>在营（开业）</ENTSTATUS><REGORG>天津市滨海新区市场监督管理局</REGORG><SUBCONAM>12000.000000</SUBCONAM><CONGROCUR>人民币元</CONGROCUR><FUNDEDRATIO>100.00%</FUNDEDRATIO><ESDATE>2009-02-25</ESDATE><NAME>张凯翔</NAME><BINVVAMOUNT>7</BINVVAMOUNT><CANDATE></CANDATE><REVDATE></REVDATE><CONFORM>货币</CONFORM><REGORGCODE>120116</REGORGCODE><CREDITCODE>911201166847202195</CREDITCODE><INDUSTRYCOCODE>7511</INDUSTRYCOCODE><INDUSTRYCONAME>农林牧渔技术推广服务</INDUSTRYCONAME><ENTNAME>天津嘉年华远洋科技有限公司</ENTNAME></ITEM></ENTINV><EXCEPTIONLIST></EXCEPTIONLIST><FILIATION></FILIATION><FINALCASE></FINALCASE><FINALSHAREHOLDER/><FRINV></FRINV><FRPOSITION></FRPOSITION><INSPECT></INSPECT><JUDICIALAIDALTER></JUDICIALAIDALTER><JUDICIALAIDDETAIL></JUDICIALAIDDETAIL><JUDICIALAID></JUDICIALAID><LIQUIDATION></LIQUIDATION><LISTEDCOMPINFO><ITEM></ITEM></LISTEDCOMPINFO><LISTEDINFO></LISTEDINFO><LISTEDMANAGER></LISTEDMANAGER><LISTEDSHAREHOLDER></LISTEDSHAREHOLDER><MORTGAGEALT></MORTGAGEALT><MORTGAGECAN></MORTGAGECAN><MORTGAGEDEBT></MORTGAGEDEBT><MORTGAGEBASIC></MORTGAGEBASIC><MORTGAGEPER></MORTGAGEPER><MORTGAGEPAWN></MORTGAGEPAWN><MORTGAGEREG></MORTGAGEREG><METADATA><ITEM><SOURCE>1</SOURCE></ITEM></METADATA><MORDETAIL></MORDETAIL><MORGUAINFO></MORGUAINFO><PERSON><ITEM><SEX></SEX><NATDATE></NATDATE><POSITION>董事长</POSITION><EMID>292dad4f1b2cf81ffd40fe86e6d93ab9</EMID><PERNAME>张贵富</PERNAME><POSITIONCODE>431A</POSITIONCODE><PERSON_ID_BOCOM></PERSON_ID_BOCOM><SEXCODE></SEXCODE><PALGORITHMID><![CDATA[V1!Tw6F42WN+ZJTys2CCSBBMxafaWhfIxn/onWVvymTaTOMKqlRjLV8nrCMcfEDoapU6QCylhEvhedl<n>IugYRVDaUw==]]></PALGORITHMID><IDENTITYCARDNT></IDENTITYCARDNT><CDID></CDID><RECORD_ID>b4f105d11104f5319b336c20fdd5c175</RECORD_ID><ENTNAME>天津乖乖投资控股集团有限公司</ENTNAME><PERSONAMOUNT>5</PERSONAMOUNT></ITEM><ITEM><SEX></SEX><NATDATE></NATDATE><POSITION>董事</POSITION><EMID>24e8e857992afddeee786b797203bd3a</EMID><PERNAME>郭美华</PERNAME><POSITIONCODE>432A</POSITIONCODE><PERSON_ID_BOCOM></PERSON_ID_BOCOM><SEXCODE></SEXCODE><PALGORITHMID><![CDATA[V1!N8qKSZD1RKrD/DwKrkZRH7oU7ujtaWp37ezlwK6vCYOKnNfSQLuZmha+buKQAX87rqd9vHBNwTFo<n>ZbxxHNSCNw==]]></PALGORITHMID><IDENTITYCARDNT></IDENTITYCARDNT><CDID></CDID><RECORD_ID>bcf1d6aeabd6a22e718a68946af67807</RECORD_ID><ENTNAME>天津乖乖投资控股集团有限公司</ENTNAME><PERSONAMOUNT>5</PERSONAMOUNT></ITEM><ITEM><SEX></SEX><NATDATE></NATDATE><POSITION>董事</POSITION><EMID>65cb55ee66b6c0cd71613150c9dcb987</EMID><PERNAME>萧家聪</PERNAME><POSITIONCODE>432A</POSITIONCODE><PERSON_ID_BOCOM></PERSON_ID_BOCOM><SEXCODE></SEXCODE><PALGORITHMID><![CDATA[V1!HlE0SzteH+dVij+1oBX6sMA6nc0KiD8Z4Hc+hnHeYXEer0/63Pc3B8K5cA3OP8xHQfqUnN9HZKw9<n>c2JRSXAZ3w==]]></PALGORITHMID><IDENTITYCARDNT></IDENTITYCARDNT><CDID></CDID><RECORD_ID>68ce07e25ce015d6380fdfdf7c38bb79</RECORD_ID><ENTNAME>天津乖乖投资控股集团有限公司</ENTNAME><PERSONAMOUNT>5</PERSONAMOUNT></ITEM><ITEM><SEX></SEX><NATDATE></NATDATE><POSITION>经理</POSITION><EMID>292dad4f1b2cf81ffd40fe86e6d93ab9</EMID><PERNAME>张贵富</PERNAME><POSITIONCODE>436A</POSITIONCODE><PERSON_ID_BOCOM></PERSON_ID_BOCOM><SEXCODE></SEXCODE><PALGORITHMID><![CDATA[V1!Tw6F42WN+ZJTys2CCSBBMxafaWhfIxn/onWVvymTaTOMKqlRjLV8nrCMcfEDoapU6QCylhEvhedl<n>IugYRVDaUw==]]></PALGORITHMID><IDENTITYCARDNT></IDENTITYCARDNT><CDID></CDID><RECORD_ID>7c42d68a15a8f9bcd957f8f86748fc8f</RECORD_ID><ENTNAME>天津乖乖投资控股集团有限公司</ENTNAME><PERSONAMOUNT>5</PERSONAMOUNT></ITEM><ITEM><SEX></SEX><NATDATE></NATDATE><POSITION>监事</POSITION><EMID>7883bd109c82405ecd53e1cd66027715</EMID><PERNAME>张凯翔</PERNAME><POSITIONCODE>408A</POSITIONCODE><PERSON_ID_BOCOM></PERSON_ID_BOCOM><SEXCODE></SEXCODE><PALGORITHMID><![CDATA[V1!PUrA0XuD609NzveORkTO8/FFcah3cNbYh/MJRRzn3K4oT/3LmJZH5CwzugqhdHsMb+qUXk/xCxBm<n>AfZDhYucOA==]]></PALGORITHMID><IDENTITYCARDNT></IDENTITYCARDNT><CDID></CDID><RECORD_ID>411089ab42d257b61c3326d4194c687c</RECORD_ID><ENTNAME>天津乖乖投资控股集团有限公司</ENTNAME><PERSONAMOUNT>5</PERSONAMOUNT></ITEM></PERSON><PUNISHBREAK></PUNISHBREAK><PUNISHED><ITEM><COURTNAME>天津市南开区人民法院</COURTNAME><CASESTATE>执行中</CASESTATE><CASECODE>(2020)津0104执908号</CASECODE><EXECMONEY>27552226</EXECMONEY><FOCUSNUMBER>0</FOCUSNUMBER><TYPE>法人或其他组织</TYPE><INAMECLEAN>天津乖乖投资控股集团有限公司</INAMECLEAN><CARDNUMCLEAN>91120116663****4097</CARDNUMCLEAN><SEXYCLEAN></SEXYCLEAN><AGECLEAN></AGECLEAN><AREANAMECLEAN></AREANAMECLEAN><YSFZD></YSFZD><REGDATECLEAN>2020-01-16</REGDATECLEAN></ITEM></PUNISHED><QUICKCANCELBASIC><ITEM></ITEM></QUICKCANCELBASIC><QUICKCANCELDISSENT></QUICKCANCELDISSENT><RELATEDPUNISHBREAK><ITEM><ENTID>067b404a6876bd072b03fe32ee17450a</ENTID><CARDNUM>9112011660****788K</CARDNUM><COURTNAME>天津市滨海新区人民法院</COURTNAME><GISTID>(2018)津0116民初637号</GISTID><CASECODE>(2019)津0116执199号</CASECODE><GISTUNIT>天津市滨海新区人民法院民一庭</GISTUNIT><DUTY><![CDATA[本院认为，原告益平拆迁公司与被告嘉年华公司签订的《天津市滨海新区轨道交通Z4线一期工程建设用地征收补偿协议》系双方当事人的真实意思表示，内容不违反法律和行政法规的强制性规定，合法有效。关于原告主张合同解除问题，依据《中华人民共和国合同法》第九十四条的规定：“有下列情形之一的，当事人可以解除合同：因不可抗力致使不能实现合同目的；在履行期限届满之前，当事人一方明确表示或者以自己的行为明确表示不履行债务；当事人一方迟延履行主要债务，经催告后在合理期限内仍未履行；当事人一方迟延履行债务或者有其他违约行为致使不能实现合同目的；法律规定的其他情形。”本案中，因涉案土地被法院查封，经过原告的催告后仍无法按时履行合同义务，致使合同目不能实现，符合上述法律规定的情形，故对原告的解除合同的诉讼请求应予支持,被告应当返还原告给付的拆迁补偿款2000万元。\\\\n原、被告在协议中约定如逾期不能完成合同约定内容则应返还原告支付的补偿款，并按每日已实际支付相应款项的万分之一标准支付违约金，该约定不违反法律规定，故对原告主张的违约金予以支持，双方虽约定为违约金实际则是原告主张被告占用补偿款期间的损失，原告主张的违约金期间尚在双方协议履行期间，协议中对被告完成约定任务的时间以及何时计算违约金并没有明确的约定，且双方一直在协商如何解决查封或者变更合同履行内容等事项，从而原告一直未正式向被告提出解除合同，行使其解除权，因此本院认为原告主张的违约金应从被告应当返还补偿款之日即合同解除之日开始计算为宜。本案原告于2018年2月22日起诉，同年3月22日被告到庭参加诉讼，该开庭时间可视为原告通知被告要求解除合同且被告已经知晓的时间，根据《中华人民共和国合同法》第九十六条之规定，双方合同应于2018年3月22日解除，原告主张的违约金应从2018年3月23日开始计算，现原告同意自2018年4月1日开始计算违约金，符合法律规定且未加重被告负担，本院予以支持。最后，被告善岛建设公司自愿向原告出具了担保函，被告善岛建设公司应当对上述被告嘉年华公司的给付义务承担连带给付责任。\\\\n综上所述，依据《中华人民共和国合同法》第六十条第一款、第九十四条、第九十六条、第九十七条、第一百零七条、《中华人民共和国担保法》第十八条之规定，判决如下：\\\\n一、确认解除原告天津滨海新区益平拆迁有限公司与被告嘉年华（天津）国际有限公司签订的《天津市滨海新区轨道交通Z4线一期工程建设用地征收补偿协议》；\\\\n二、被告嘉年华（天津）国际有限公司于本判决生效后十日内返还原告天津滨海新区益平拆迁有限公司拆迁补偿款20，000，000元；\\\\n三、被告嘉年华（天津）国际有限公司于本判决生效后十日内支付原告天津滨海新区益平拆迁有限公司自2018年4月1日至实际还清补偿款之日止的违约金（以未给付补偿款为基数，按每日万分之一计算）；\\\\n四、被告善岛建设（天津）有限公司对被告嘉年华（天津）国际有限公司上述给付义务承担连带责任；\\\\n五、驳回原告天津滨海新区益平拆迁有限公司其他诉讼请求。]]></DUTY><PERFORMANCE>全部未履行</PERFORMANCE><PERFORMEDPART>暂无</PERFORMEDPART><UNPERFORMPART>暂无</UNPERFORMPART><DISRUPTTYPENAME>违反财产报告制度</DISRUPTTYPENAME><FOCUSNUMBER></FOCUSNUMBER><BUSINESSENTITY></BUSINESSENTITY><TYPE>法人或其他组织</TYPE><INAMECLEAN>嘉年华(天津)国际有限公司</INAMECLEAN><SEXYCLEAN></SEXYCLEAN><AGECLEAN></AGECLEAN><AREANAMECLEAN>天津</AREANAMECLEAN><YSFZD></YSFZD><REGDATECLEAN>2019-02-25</REGDATECLEAN><PUBLISHDATECLEAN>2019-06-14</PUBLISHDATECLEAN><EXITDATE></EXITDATE><EMID></EMID><PALGORITHMID></PALGORITHMID><CASESTATE></CASESTATE></ITEM><ITEM><ENTID>067b404a6876bd072b03fe32ee17450a</ENTID><CARDNUM>60051578-8</CARDNUM><COURTNAME>天津市北辰区人民法院</COURTNAME><GISTID>(2017)津0113民初315号</GISTID><CASECODE>(2017)津0113执1972号</CASECODE><GISTUNIT>天津市北辰区人民法院小淀法庭</GISTUNIT><DUTY>欠款1450万元及利息</DUTY><PERFORMANCE>全部未履行</PERFORMANCE><PERFORMEDPART>暂无</PERFORMEDPART><UNPERFORMPART>暂无</UNPERFORMPART><DISRUPTTYPENAME>有履行能力而拒不履行生效法律文书确定义务</DISRUPTTYPENAME><FOCUSNUMBER></FOCUSNUMBER><BUSINESSENTITY>张贵富</BUSINESSENTITY><TYPE>法人或其他组织</TYPE><INAMECLEAN>嘉年华(天津)国际有限公司</INAMECLEAN><SEXYCLEAN></SEXYCLEAN><AGECLEAN></AGECLEAN><AREANAMECLEAN>天津</AREANAMECLEAN><YSFZD></YSFZD><REGDATECLEAN>2017-08-23</REGDATECLEAN><PUBLISHDATECLEAN>2017-12-07</PUBLISHDATECLEAN><EXITDATE></EXITDATE><EMID></EMID><PALGORITHMID></PALGORITHMID><CASESTATE></CASESTATE></ITEM></RELATEDPUNISHBREAK><RELATEDPUNISHED><ITEM><COURTNAME>天津市第一中级人民法院</COURTNAME><CASESTATE>执行中</CASESTATE><CASECODE>(2020)津01执161号</CASECODE><EXECMONEY>97887728</EXECMONEY><FOCUSNUMBER>0</FOCUSNUMBER><TYPE>法人或其他组织</TYPE><INAMECLEAN>嘉年华(天津)国际有限公司</INAMECLEAN><CARDNUMCLEAN>91120116600****788K</CARDNUMCLEAN><SEXYCLEAN></SEXYCLEAN><AGECLEAN></AGECLEAN><AREANAMECLEAN></AREANAMECLEAN><YSFZD></YSFZD><REGDATECLEAN>2020-04-01</REGDATECLEAN><ENTID>067b404a6876bd072b03fe32ee17450a</ENTID><EMID></EMID><PALGORITHMID></PALGORITHMID></ITEM><ITEM><COURTNAME>天津市南开区人民法院</COURTNAME><CASESTATE>执行中</CASESTATE><CASECODE>(2020)津0104执908号</CASECODE><EXECMONEY>27552226</EXECMONEY><FOCUSNUMBER>0</FOCUSNUMBER><TYPE>法人或其他组织</TYPE><INAMECLEAN>嘉年华(天津)国际有限公司</INAMECLEAN><CARDNUMCLEAN>91120116600****788K</CARDNUMCLEAN><SEXYCLEAN></SEXYCLEAN><AGECLEAN></AGECLEAN><AREANAMECLEAN></AREANAMECLEAN><YSFZD></YSFZD><REGDATECLEAN>2020-01-16</REGDATECLEAN><ENTID>067b404a6876bd072b03fe32ee17450a</ENTID><EMID></EMID><PALGORITHMID></PALGORITHMID></ITEM><ITEM><COURTNAME>天津市南开区人民法院</COURTNAME><CASESTATE>执行中</CASESTATE><CASECODE>(2020)津0104执908号</CASECODE><EXECMONEY>27552226</EXECMONEY><FOCUSNUMBER>0</FOCUSNUMBER><TYPE>法人或其他组织</TYPE><INAMECLEAN>天津嘉年华数位广告传媒有限公司</INAMECLEAN><CARDNUMCLEAN>91120118341****756R</CARDNUMCLEAN><SEXYCLEAN></SEXYCLEAN><AGECLEAN></AGECLEAN><AREANAMECLEAN></AREANAMECLEAN><YSFZD></YSFZD><REGDATECLEAN>2020-01-16</REGDATECLEAN><ENTID>8e3378efb8de4965208b37146fe12989</ENTID><EMID></EMID><PALGORITHMID></PALGORITHMID></ITEM><ITEM><COURTNAME>天津市第二中级人民法院</COURTNAME><CASESTATE>执行中</CASESTATE><CASECODE>(2020)津02执57号</CASECODE><EXECMONEY>30777360</EXECMONEY><FOCUSNUMBER>0</FOCUSNUMBER><TYPE>法人或其他组织</TYPE><INAMECLEAN>嘉年华(天津)国际有限公司</INAMECLEAN><CARDNUMCLEAN>91120116600****788K</CARDNUMCLEAN><SEXYCLEAN></SEXYCLEAN><AGECLEAN></AGECLEAN><AREANAMECLEAN></AREANAMECLEAN><YSFZD></YSFZD><REGDATECLEAN>2020-01-13</REGDATECLEAN><ENTID>067b404a6876bd072b03fe32ee17450a</ENTID><EMID></EMID><PALGORITHMID></PALGORITHMID></ITEM><ITEM><COURTNAME>天津市第一中级人民法院</COURTNAME><CASESTATE>执行中</CASESTATE><CASECODE>(2019)津01执443号</CASECODE><EXECMONEY>14989481</EXECMONEY><FOCUSNUMBER>0</FOCUSNUMBER><TYPE>法人或其他组织</TYPE><INAMECLEAN>嘉年华(天津)国际有限公司</INAMECLEAN><CARDNUMCLEAN>91120116600****788K</CARDNUMCLEAN><SEXYCLEAN></SEXYCLEAN><AGECLEAN></AGECLEAN><AREANAMECLEAN></AREANAMECLEAN><YSFZD></YSFZD><REGDATECLEAN>2019-04-24</REGDATECLEAN><ENTID>067b404a6876bd072b03fe32ee17450a</ENTID><EMID></EMID><PALGORITHMID></PALGORITHMID></ITEM></RELATEDPUNISHED><SHAREHOLDER><ITEM><ENTID>fad7c4c8b3319812f60924ff80ae1ae3</ENTID><INVTYPE>法人股东</INVTYPE><COUNTRY>中国</COUNTRY><SUBCONAM>1680.000000</SUBCONAM><ACCONAM>1680.000000</ACCONAM><CONFORM>货币</CONFORM><CONDATE>2007-07-17</CONDATE><EMID></EMID><SHANAME>天津开发区永莲物业管理有限公司</SHANAME><FUNDEDRATIO>60.00%</FUNDEDRATIO><INVTYPECODE>10</INVTYPECODE><CONFORMCODE>1</CONFORMCODE><COUNTRYCODE>156</COUNTRYCODE><REGCAPCUR>人民币元</REGCAPCUR><CURRENCYCODE>156</CURRENCYCODE><PERSON_ID_BOCOM></PERSON_ID_BOCOM><PALGORITHMID></PALGORITHMID><SUMCONAM>2800.000000</SUMCONAM><INVSUMFUNDEDRATIO>100.00%</INVSUMFUNDEDRATIO><REGNO>120191000016897</REGNO><CREDITCODE>911201167413572775</CREDITCODE><INVAMOUNT>2</INVAMOUNT><IDENTITYCARDNT></IDENTITYCARDNT><IDENTITY></IDENTITY><CDID></CDID><RECORD_ID>0c2c15831ad0b2a2e345efc9fdbdf8ba</RECORD_ID></ITEM><ITEM><ENTID>d4b8242508746531797445fd13bcc5ef</ENTID><INVTYPE>法人股东</INVTYPE><COUNTRY>中国</COUNTRY><SUBCONAM>1120.000000</SUBCONAM><ACCONAM>1120.000000</ACCONAM><CONFORM>货币</CONFORM><CONDATE>2007-07-17</CONDATE><EMID></EMID><SHANAME>天津鸿海大荣进出口贸易有限公司</SHANAME><FUNDEDRATIO>40.00%</FUNDEDRATIO><INVTYPECODE>10</INVTYPECODE><CONFORMCODE>1</CONFORMCODE><COUNTRYCODE>156</COUNTRYCODE><REGCAPCUR>人民币元</REGCAPCUR><CURRENCYCODE>156</CURRENCYCODE><PERSON_ID_BOCOM></PERSON_ID_BOCOM><PALGORITHMID></PALGORITHMID><SUMCONAM>2800.000000</SUMCONAM><INVSUMFUNDEDRATIO>100.00%</INVSUMFUNDEDRATIO><REGNO>120191000016821</REGNO><CREDITCODE>9112011675811612XG</CREDITCODE><INVAMOUNT>2</INVAMOUNT><IDENTITYCARDNT></IDENTITYCARDNT><IDENTITY></IDENTITY><CDID></CDID><RECORD_ID>6f938bd6f8076438e872ccc693123853</RECORD_ID></ITEM></SHAREHOLDER><SHARESFROST></SHARESFROST><SHARESIMPAWN></SHARESIMPAWN><STOCKPAWNALT></STOCKPAWNALT><STOCKPAWN></STOCKPAWN><STOCKPAWNREV></STOCKPAWNREV><TRADEMARK></TRADEMARK><YEARREPORTANASSETSINFO></YEARREPORTANASSETSINFO><YEARREPORTALTER><ITEM><ANCHEID>9ac8d456650cf4579c5db3362b5a8c6e</ANCHEID><ALITEM>注册号</ALITEM><ALTBE>130</ALTBE><ALTAF>9113050655608617XF</ALTAF><ALTDATE>2018-03-16</ALTDATE></ITEM><ITEM><ANCHEID>9ac8d456650cf4579c5db3362b5a8c6e</ANCHEID><ALITEM>注册号</ALITEM><ALTBE>91220</ALTBE><ALTAF>912202940597663347</ALTAF><ALTDATE>2018-03-16</ALTDATE></ITEM></YEARREPORTALTER><YEARREPORTSOCSEC><ITEM><ANCHEID>ede95f0658f1f1b70ecbd7ba80a00ed5</ANCHEID><SO110>0</SO110><SO210>0</SO210><SO310>0</SO310><SO410>0</SO410><SO510>0</SO510><TOTALWAGES_SO110></TOTALWAGES_SO110><TOTALWAGES_SO210></TOTALWAGES_SO210><TOTALWAGES_SO310></TOTALWAGES_SO310><TOTALWAGES_SO410></TOTALWAGES_SO410><TOTALWAGES_SO510></TOTALWAGES_SO510><TOTALPAYMENT_SO110></TOTALPAYMENT_SO110><TOTALPAYMENT_SO210></TOTALPAYMENT_SO210><TOTALPAYMENT_SO310></TOTALPAYMENT_SO310><TOTALPAYMENT_SO410></TOTALPAYMENT_SO410><TOTALPAYMENT_SO510></TOTALPAYMENT_SO510><UNPAIDSOCIALINS_SO110></UNPAIDSOCIALINS_SO110><UNPAIDSOCIALINS_SO210></UNPAIDSOCIALINS_SO210><UNPAIDSOCIALINS_SO310></UNPAIDSOCIALINS_SO310><UNPAIDSOCIALINS_SO410></UNPAIDSOCIALINS_SO410><UNPAIDSOCIALINS_SO510></UNPAIDSOCIALINS_SO510></ITEM></YEARREPORTSOCSEC><YEARREPORT><ITEM><YEARREPORTALTERSTOCKINFO/><YEARREPORTFORGUARANTEEINFO/><YEARREPORTWEBSITEINFO/><YEARREPORTBASIC><ITEM><ANCHEID>ede95f0658f1f1b70ecbd7ba80a00ed5</ANCHEID><ANCHEDATE>2019-03-06</ANCHEDATE><ANCHEYEAR>2018</ANCHEYEAR><REGNO>120191000002366</REGNO><CREDITNO>911201166630834097</CREDITNO><ENTNAME>天津乖乖投资控股集团有限公司</ENTNAME><TEL>022-66253373</TEL><ADDR>天津开发区黄海路118号</ADDR><POSTALCODE>300457</POSTALCODE><EMAIL>970703880@qq.com</EMAIL><BUSST>开业</BUSST><WOMEMPNUM></WOMEMPNUM><MAINBUSIACT>以自有资金对工业、商业、能源建设、交通运输、房地产、证券行业、仓储服务、高新技术产业的投资。</MAINBUSIACT><HOLDINGSMSG_CN>其他</HOLDINGSMSG_CN></ITEM></YEARREPORTBASIC><YEARREPORTFORINVESTMENT><ITEM><ANCHEID>ede95f0658f1f1b70ecbd7ba80a00ed5</ANCHEID><ENTNAME>天津乖乖粮油有限公司</ENTNAME><REGNO></REGNO><CREDITNO>91120224681868322N</CREDITNO></ITEM><ITEM><ANCHEID>ede95f0658f1f1b70ecbd7ba80a00ed5</ANCHEID><ENTNAME>嘉年华(天津)国际有限公司</ENTNAME><REGNO></REGNO><CREDITNO>91120116600515788K</CREDITNO></ITEM><ITEM><ANCHEID>ede95f0658f1f1b70ecbd7ba80a00ed5</ANCHEID><ENTNAME>吉林乖乖食品有限公司</ENTNAME><REGNO></REGNO><CREDITNO>912202940597663347</CREDITNO></ITEM><ITEM><ANCHEID>ede95f0658f1f1b70ecbd7ba80a00ed5</ANCHEID><ENTNAME>天津嘉年华远洋科技有限公司</ENTNAME><REGNO></REGNO><CREDITNO>911201166847202195</CREDITNO></ITEM><ITEM><ANCHEID>ede95f0658f1f1b70ecbd7ba80a00ed5</ANCHEID><ENTNAME>河北嘉荣房地产开发有限公司</ENTNAME><REGNO></REGNO><CREDITNO>9113050655608617XF</CREDITNO></ITEM><ITEM><ANCHEID>ede95f0658f1f1b70ecbd7ba80a00ed5</ANCHEID><ENTNAME>乖乖嘉年华(天津)食品有限公司</ENTNAME><REGNO></REGNO><CREDITNO>911202246688230745</CREDITNO></ITEM></YEARREPORTFORINVESTMENT><YEARREPORTSUBCAPITAL><ITEM><ANCHEID>ede95f0658f1f1b70ecbd7ba80a00ed5</ANCHEID><INV>天津鸿海大荣进出口进出口贸易有限公司</INV><LISUBCONAM>1120.000000</LISUBCONAM><CONDATE>2007-07-02</CONDATE><CONFORM></CONFORM><CURRENCY></CURRENCY></ITEM><ITEM><ANCHEID>ede95f0658f1f1b70ecbd7ba80a00ed5</ANCHEID><INV>天津开发区永莲物业管理有限公司</INV><LISUBCONAM>1680.000000</LISUBCONAM><CONDATE>2007-07-02</CONDATE><CONFORM></CONFORM><CURRENCY></CURRENCY></ITEM></YEARREPORTSUBCAPITAL><YEARREPORTPAIDUPCAPITAL><ITEM><ANCHEID>ede95f0658f1f1b70ecbd7ba80a00ed5</ANCHEID><INV>天津鸿海大荣进出口进出口贸易有限公司</INV><LIACCONAM>1120.000000</LIACCONAM><CONDATE>2007-07-09</CONDATE><CONFORM></CONFORM><CURRENCY></CURRENCY></ITEM><ITEM><ANCHEID>ede95f0658f1f1b70ecbd7ba80a00ed5</ANCHEID><INV>天津开发区永莲物业管理有限公司</INV><LIACCONAM>1680.000000</LIACCONAM><CONDATE>2007-07-06</CONDATE><CONFORM></CONFORM><CURRENCY></CURRENCY></ITEM></YEARREPORTPAIDUPCAPITAL></ITEM><ITEM><YEARREPORTALTERSTOCKINFO/><YEARREPORTFORGUARANTEEINFO/><YEARREPORTWEBSITEINFO/><YEARREPORTBASIC><ITEM><ANCHEID>9ac8d456650cf4579c5db3362b5a8c6e</ANCHEID><ANCHEDATE>2018-03-16</ANCHEDATE><ANCHEYEAR>2017</ANCHEYEAR><REGNO>120191000002366</REGNO><CREDITNO>911201166630834097</CREDITNO><ENTNAME>天津乖乖投资控股集团有限公司</ENTNAME><TEL>022-66253373</TEL><ADDR>天津开发区黄海路118号</ADDR><POSTALCODE>300457</POSTALCODE><EMAIL>zjs@guaiguai.cn</EMAIL><BUSST>开业</BUSST><WOMEMPNUM></WOMEMPNUM><MAINBUSIACT></MAINBUSIACT><HOLDINGSMSG_CN></HOLDINGSMSG_CN></ITEM></YEARREPORTBASIC></ITEM><ITEM><YEARREPORTALTERSTOCKINFO/><YEARREPORTFORGUARANTEEINFO/><YEARREPORTWEBSITEINFO/><YEARREPORTBASIC><ITEM><ANCHEID>36bd125903dc5bcb36895d5ba8ff7874</ANCHEID><ANCHEDATE>2017-05-26</ANCHEDATE><ANCHEYEAR>2016</ANCHEYEAR><REGNO>120191000002366</REGNO><CREDITNO>911201166630834097</CREDITNO><ENTNAME>天津乖乖投资控股集团有限公司</ENTNAME><TEL>022-66252677</TEL><ADDR>天津开发区黄海路118号</ADDR><POSTALCODE>300457</POSTALCODE><EMAIL>zjs@guaiguai.cn</EMAIL><BUSST>开业</BUSST><WOMEMPNUM></WOMEMPNUM><MAINBUSIACT></MAINBUSIACT><HOLDINGSMSG_CN></HOLDINGSMSG_CN></ITEM></YEARREPORTBASIC></ITEM></YEARREPORT></DATA>";
            Map<String, Object> xml2Map = toMap(xmlStr);
            System.out.println(JSON.toJSONString(xml2Map));
            System.out.println("==============================");
            xmlStr = toXml(xml2Map);
            System.out.println(xmlStr);
        }
    }
